# Generated by Django 4.1.3 on 2022-12-08 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_students_is_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_employee',
            field=models.BooleanField(blank=True, default='False', null=True),
        ),
    ]
