# Generated by Django 4.1.3 on 2022-12-11 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_employee_is_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='is_employee',
        ),
        migrations.RemoveField(
            model_name='students',
            name='is_employee',
        ),
    ]
