# Generated by Django 4.1.3 on 2022-12-12 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_remove_employee_is_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_pic',
            field=models.URLField(blank=True, default='https://media.istockphoto.com/id/1300845620/vector/user-icon-flat-isolated-on-white-background-user-symbol-vector-illustration.jpg?s=612x612&w=0&k=20&c=yBeyba0hUkh14_jgv1OKqIH0CCSWU_4ckRkAoy2p73o=', null=True),
        ),
    ]
