# Generated by Django 4.1.3 on 2022-12-12 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_alter_employee_employee_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
