# Generated by Django 4.1.3 on 2022-12-15 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_employee_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='bg_personal_number',
            field=models.CharField(blank=True, default='', max_length=15, null=True, verbose_name='ЕГН'),
        ),
        migrations.AlterField(
            model_name='students',
            name='city',
            field=models.CharField(blank=True, default='', max_length=15, null=True, verbose_name='Град'),
        ),
        migrations.AlterField(
            model_name='students',
            name='country_of_birth',
            field=models.CharField(blank=True, default='', max_length=15, null=True, verbose_name='Държава на раждане'),
        ),
        migrations.AlterField(
            model_name='students',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='dd-mm-yyyy', null=True, verbose_name='Дата на раждане'),
        ),
        migrations.AlterField(
            model_name='students',
            name='email',
            field=models.CharField(blank=True, default='', max_length=40, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='students',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=15, null=True, verbose_name='Име'),
        ),
        migrations.AlterField(
            model_name='students',
            name='foreign_university',
            field=models.CharField(blank=True, default='', max_length=15, null=True, verbose_name='Чуждестранен университет'),
        ),
        migrations.AlterField(
            model_name='students',
            name='how_to_reach',
            field=models.CharField(blank=True, default='', max_length=15, null=True, verbose_name='Как да комуникираме?'),
        ),
        migrations.AlterField(
            model_name='students',
            name='id_passport_number',
            field=models.CharField(blank=True, default='', max_length=15, null=True, verbose_name='Номер на паспорт'),
        ),
        migrations.AlterField(
            model_name='students',
            name='is_fulltime_student',
            field=models.BooleanField(blank=True, null=True, verbose_name='Студент "Редовно обучение"'),
        ),
        migrations.AlterField(
            model_name='students',
            name='is_received_visa',
            field=models.BooleanField(blank=True, null=True, verbose_name='Получена виза'),
        ),
        migrations.AlterField(
            model_name='students',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=15, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='students',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=15, null=True, verbose_name='Презиме'),
        ),
        migrations.AlterField(
            model_name='students',
            name='nationality',
            field=models.CharField(blank=True, default='', max_length=15, null=True, verbose_name='Националност'),
        ),
        migrations.AlterField(
            model_name='students',
            name='passport_date_of_issue',
            field=models.DateField(blank=True, null=True, verbose_name='Дата на издаване на паспорт'),
        ),
        migrations.AlterField(
            model_name='students',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=15, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='students',
            name='place_of_birth',
            field=models.CharField(blank=True, default='', max_length=15, null=True, verbose_name='Място на раждане'),
        ),
        migrations.AlterField(
            model_name='students',
            name='province',
            field=models.CharField(blank=True, default='', max_length=15, null=True, verbose_name='Област'),
        ),
        migrations.AlterField(
            model_name='students',
            name='search_job_pref',
            field=models.CharField(blank=True, default='', max_length=15, null=True, verbose_name='Предпочитана работа'),
        ),
        migrations.AlterField(
            model_name='students',
            name='street',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Улица/ж.к.'),
        ),
        migrations.AlterField(
            model_name='students',
            name='university',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Университет'),
        ),
        migrations.AlterField(
            model_name='students',
            name='visa_photo',
            field=models.URLField(blank=True, null=True, verbose_name='Снимка за ВИЗА'),
        ),
        migrations.AlterField(
            model_name='students',
            name='year_of_education',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Курс'),
        ),
    ]
