# Generated by Django 4.1.3 on 2022-12-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0008_alter_students_middle_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=15, null=True, verbose_name='Презиме'),
        ),
        migrations.AlterField(
            model_name='students',
            name='year_of_education',
            field=models.PositiveIntegerField(blank=True, default='', null=True, verbose_name='Курс'),
        ),
    ]
