# Generated by Django 4.1.3 on 2022-12-16 08:33

import aimtravel_project.user_profile.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0009_alter_students_middle_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='file_field',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_first_name',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[aimtravel_project.user_profile.validators.only_letters]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_last_name',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[aimtravel_project.user_profile.validators.only_letters]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_phone',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[aimtravel_project.user_profile.validators.only_digits]),
        ),
        migrations.AlterField(
            model_name='students',
            name='bg_personal_number',
            field=models.CharField(blank=True, default='', max_length=15, null=True, validators=[aimtravel_project.user_profile.validators.only_digits], verbose_name='ЕГН'),
        ),
        migrations.AlterField(
            model_name='students',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=15, null=True, validators=[aimtravel_project.user_profile.validators.only_letters], verbose_name='Име'),
        ),
        migrations.AlterField(
            model_name='students',
            name='foreign_university',
            field=models.CharField(blank=True, default='', max_length=15, null=True, validators=[aimtravel_project.user_profile.validators.only_letters], verbose_name='Чуждестранен университет'),
        ),
        migrations.AlterField(
            model_name='students',
            name='id_passport_number',
            field=models.CharField(blank=True, default='', max_length=15, null=True, validators=[aimtravel_project.user_profile.validators.only_digits], verbose_name='Номер на паспорт'),
        ),
        migrations.AlterField(
            model_name='students',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=15, null=True, validators=[aimtravel_project.user_profile.validators.only_letters], verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='students',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=15, null=True, validators=[aimtravel_project.user_profile.validators.only_letters], verbose_name='Презиме'),
        ),
        migrations.AlterField(
            model_name='students',
            name='nationality',
            field=models.CharField(blank=True, default='', max_length=15, null=True, validators=[aimtravel_project.user_profile.validators.only_letters], verbose_name='Националност'),
        ),
        migrations.AlterField(
            model_name='students',
            name='passport_date_of_issue',
            field=models.DateField(blank=True, default='', null=True, verbose_name='Дата на издаване'),
        ),
        migrations.AlterField(
            model_name='students',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=15, null=True, validators=[aimtravel_project.user_profile.validators.only_digits], verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='students',
            name='place_of_birth',
            field=models.CharField(blank=True, default='', max_length=15, null=True, validators=[aimtravel_project.user_profile.validators.only_letters], verbose_name='Място на раждане'),
        ),
        migrations.AlterField(
            model_name='students',
            name='university',
            field=models.CharField(blank=True, default='', max_length=30, null=True, validators=[aimtravel_project.user_profile.validators.only_letters], verbose_name='Университет'),
        ),
    ]
