# Generated by Django 4.1.3 on 2022-12-17 15:12

import aimtravel_project.user_profile.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0011_alter_students_file_field_alter_students_visa_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='first_name',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[aimtravel_project.user_profile.validators.only_letters], verbose_name='Име'),
        ),
        migrations.AlterField(
            model_name='students',
            name='last_name',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[aimtravel_project.user_profile.validators.only_letters], verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='students',
            name='middle_name',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[aimtravel_project.user_profile.validators.only_letters], verbose_name='Презиме'),
        ),
        migrations.AlterField(
            model_name='students',
            name='passport_date_of_issue',
            field=models.DateField(blank=True, null=True, verbose_name='Дата на издаване'),
        ),
        migrations.AlterField(
            model_name='students',
            name='year_of_education',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Курс'),
        ),
    ]
