# Generated by Django 4.1.3 on 2022-12-17 16:11

import aimtravel_project.user_profile.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0012_alter_students_first_name_alter_students_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='is_staff',
        ),
        migrations.AlterField(
            model_name='students',
            name='bg_personal_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[aimtravel_project.user_profile.validators.only_digits], verbose_name='ЕГН'),
        ),
        migrations.AlterField(
            model_name='students',
            name='city',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Град'),
        ),
        migrations.AlterField(
            model_name='students',
            name='country_of_birth',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Държава на раждане'),
        ),
        migrations.AlterField(
            model_name='students',
            name='email',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='students',
            name='foreign_university',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[aimtravel_project.user_profile.validators.only_letters], verbose_name='Чуждестранен университет'),
        ),
        migrations.AlterField(
            model_name='students',
            name='how_to_reach',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Как да комуникираме?'),
        ),
        migrations.AlterField(
            model_name='students',
            name='id_passport_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[aimtravel_project.user_profile.validators.only_digits], verbose_name='Номер на паспорт'),
        ),
        migrations.AlterField(
            model_name='students',
            name='nationality',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[aimtravel_project.user_profile.validators.only_letters], verbose_name='Националност'),
        ),
        migrations.AlterField(
            model_name='students',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[aimtravel_project.user_profile.validators.only_digits], verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='students',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[aimtravel_project.user_profile.validators.only_letters], verbose_name='Място на раждане'),
        ),
        migrations.AlterField(
            model_name='students',
            name='province',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Област'),
        ),
        migrations.AlterField(
            model_name='students',
            name='search_job_pref',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Предпочитана работа'),
        ),
        migrations.AlterField(
            model_name='students',
            name='street',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Улица/ж.к.'),
        ),
        migrations.AlterField(
            model_name='students',
            name='university',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[aimtravel_project.user_profile.validators.only_letters], verbose_name='Университет'),
        ),
    ]
