# Generated by Django 4.1.3 on 2022-12-17 16:56

import aimtravel_project.user_profile.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0013_remove_employee_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_first_name',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[aimtravel_project.user_profile.validators.only_letters], verbose_name='Име'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_last_name',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[aimtravel_project.user_profile.validators.only_letters], verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_role',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='students',
            name='bg_personal_number',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[aimtravel_project.user_profile.validators.only_digits], verbose_name='ЕГН'),
        ),
        migrations.AlterField(
            model_name='students',
            name='foreign_university',
            field=models.CharField(blank=True, max_length=40, null=True, validators=[aimtravel_project.user_profile.validators.only_letters], verbose_name='Чуждестранен университет'),
        ),
        migrations.AlterField(
            model_name='students',
            name='university',
            field=models.CharField(blank=True, max_length=40, null=True, validators=[aimtravel_project.user_profile.validators.only_letters], verbose_name='Университет'),
        ),
    ]
