# Generated by Django 4.1.3 on 2022-12-06 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer_name', models.CharField(max_length=25, null=True)),
                ('employer_city', models.CharField(max_length=15, null=True)),
                ('employer_state', models.CharField(max_length=2, null=True)),
                ('employer_history', models.TextField(max_length=250, null=True)),
                ('employer_photo', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
