# Generated by Django 4.1.3 on 2022-12-08 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='ranking',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
