# Generated by Django 4.1.3 on 2022-12-08 22:51

import aimtravel_project.web.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_joboffer_ranking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='employer_city',
            field=models.CharField(max_length=15, null=True, verbose_name='Град'),
        ),
        migrations.AlterField(
            model_name='company',
            name='employer_history',
            field=models.TextField(max_length=250, null=True, verbose_name='Кратка история'),
        ),
        migrations.AlterField(
            model_name='company',
            name='employer_name',
            field=models.CharField(max_length=25, null=True, verbose_name='Работодател'),
        ),
        migrations.AlterField(
            model_name='company',
            name='employer_photo',
            field=models.URLField(blank=True, null=True, verbose_name='Снимка-URL'),
        ),
        migrations.AlterField(
            model_name='company',
            name='employer_state',
            field=models.CharField(max_length=2, null=True, verbose_name='Щат'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='ranking',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, validators=[aimtravel_project.web.validators.max_value]),
        ),
        migrations.AlterField(
            model_name='prices',
            name='price',
            field=models.FloatField(verbose_name='Цена:'),
        ),
        migrations.AlterField(
            model_name='prices',
            name='price_description',
            field=models.TextField(blank=True, help_text='Моля добавете описание', null=True, verbose_name='В цената е включено:'),
        ),
        migrations.AlterField(
            model_name='prices',
            name='pricing_type',
            field=models.CharField(blank=True, choices=[('Self Arranged', 'Self Arranged'), ('Full Placement Standard', 'Full Placement Standard'), ('Premium Full Placement', 'Premium Full Placement')], default='Full Placement Standard', max_length=25, null=True, verbose_name='Ценови план:'),
        ),
    ]
