# Generated by Django 4.1.3 on 2022-12-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_company_employer_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalservices',
            name='service_description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание на услугата'),
        ),
        migrations.AlterField(
            model_name='additionalservices',
            name='service_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена на услугата'),
        ),
        migrations.AlterField(
            model_name='additionalservices',
            name='service_type',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Вид услуга'),
        ),
    ]
