# Generated by Django 4.1.3 on 2022-12-17 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_additionalservices_service_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='employer_city',
            field=models.CharField(max_length=20, null=True, verbose_name='Град'),
        ),
        migrations.AlterField(
            model_name='company',
            name='employer_name',
            field=models.CharField(max_length=30, null=True, verbose_name='Работодател'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='sponsor',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Спонсор'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='state',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Щат'),
        ),
    ]
